name: Demo-1
on: push



jobs:

 vars:
  runs-on: ubuntu-latest
  steps:
    - name: variables
      run: echo "Hello {{ var.USER_NAME }}"
      
 secrets:
   runs-on: ubuntu-latest
   steps:
    - name: secrets
      run: echo "Password is {{ secrets.USER_PWD }}"

 
       
