name: Demo-1
on: workflow_dispatch

jobs:

 Code:
  runs-on: ubuntu-latest
  steps:
    - name: Code
      run: echo "Code pulled successfully"
      
 Build:
   runs-on: ubuntu-latest
   needs: Code
   steps:
    - name: Build stage
      run: echo "Build completed"

 test:
  runs-on: ubuntu-latest
  needs: Build
  steps:
    - name: test stage
      run: "test completed"
       
